// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: comdex/claim/v1beta1/claim.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/x/bank/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Action int32

const (
	ActionLock        Action = 0
	ActionVote        Action = 1
	ActionCreateVault Action = 2
	ActionDeposit     Action = 3
)

var Action_name = map[int32]string{
	0: "ActionLock",
	1: "ActionVote",
	2: "ActionCreateVault",
	3: "ActionDeposit",
}

var Action_value = map[string]int32{
	"ActionLock":        0,
	"ActionVote":        1,
	"ActionCreateVault": 2,
	"ActionDeposit":     3,
}

func (x Action) String() string {
	return proto.EnumName(Action_name, int32(x))
}

func (Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0bef253dc1519407, []int{0}
}

// A Claim Records is the metadata of claim data per address
type ClaimRecord struct {
	// address of claim user
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty" yaml:"address"`
	// total initial claimable amount for the user
	InitialClaimableAmount github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,2,rep,name=initial_claimable_amount,json=initialClaimableAmount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"initial_claimable_amount" yaml:"initial_claimable_amount"`
	// true if action is completed
	// index of bool in array refers to action enum #
	ActionCompleted []bool `protobuf:"varint,3,rep,packed,name=action_completed,json=actionCompleted,proto3" json:"action_completed,omitempty" yaml:"action_completed"`
}

func (m *ClaimRecord) Reset()         { *m = ClaimRecord{} }
func (m *ClaimRecord) String() string { return proto.CompactTextString(m) }
func (*ClaimRecord) ProtoMessage()    {}
func (*ClaimRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_0bef253dc1519407, []int{0}
}
func (m *ClaimRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClaimRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClaimRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ClaimRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClaimRecord.Merge(m, src)
}
func (m *ClaimRecord) XXX_Size() int {
	return m.Size()
}
func (m *ClaimRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ClaimRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ClaimRecord proto.InternalMessageInfo

func (m *ClaimRecord) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ClaimRecord) GetInitialClaimableAmount() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.InitialClaimableAmount
	}
	return nil
}

func (m *ClaimRecord) GetActionCompleted() []bool {
	if m != nil {
		return m.ActionCompleted
	}
	return nil
}

func init() {
	proto.RegisterEnum("comdex.claim.v1beta1.Action", Action_name, Action_value)
	proto.RegisterType((*ClaimRecord)(nil), "comdex.claim.v1beta1.ClaimRecord")
}

func init() { proto.RegisterFile("comdex/claim/v1beta1/claim.proto", fileDescriptor_0bef253dc1519407) }

var fileDescriptor_0bef253dc1519407 = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xbf, 0x6e, 0xd4, 0x30,
	0x18, 0x4f, 0xee, 0x50, 0x01, 0x57, 0x94, 0xd4, 0x2a, 0x70, 0xdc, 0xe0, 0x84, 0x4c, 0x11, 0xa2,
	0xb1, 0x0a, 0x1b, 0x5b, 0x13, 0x16, 0x10, 0x53, 0x90, 0x2a, 0xc4, 0x72, 0x72, 0x1c, 0x37, 0x58,
	0x97, 0xe4, 0x8b, 0x62, 0x1f, 0xa2, 0x6f, 0xc0, 0xc8, 0x3b, 0xb0, 0x20, 0x46, 0x9e, 0xa2, 0x63,
	0x47, 0xa6, 0x03, 0xdd, 0xbd, 0x41, 0x9f, 0x00, 0x25, 0x76, 0x5a, 0x81, 0xd4, 0x29, 0xfe, 0xfd,
	0xd1, 0x2f, 0xbf, 0xcf, 0xfe, 0x50, 0xc0, 0xa1, 0x2e, 0xc4, 0x67, 0xca, 0x2b, 0x26, 0x6b, 0xfa,
	0xe9, 0x28, 0x17, 0x9a, 0x1d, 0x19, 0x14, 0xb7, 0x1d, 0x68, 0xc0, 0x07, 0xc6, 0x11, 0x1b, 0xce,
	0x3a, 0xe6, 0x07, 0x25, 0x94, 0x30, 0x18, 0x68, 0x7f, 0x32, 0xde, 0x39, 0xe1, 0xa0, 0x6a, 0x50,
	0x34, 0x67, 0x4a, 0x5c, 0x87, 0x81, 0x6c, 0xac, 0xfe, 0xe4, 0x4a, 0x6f, 0x96, 0x57, 0x7a, 0x29,
	0x1a, 0xa1, 0xa4, 0x32, 0x96, 0xf0, 0xe7, 0x04, 0xed, 0xa6, 0xfd, 0xaf, 0x32, 0xc1, 0xa1, 0x2b,
	0xf0, 0x33, 0x74, 0x9b, 0x15, 0x45, 0x27, 0x94, 0x9a, 0xb9, 0x81, 0x1b, 0xdd, 0x4d, 0xf0, 0xe5,
	0xda, 0xdf, 0x3b, 0x63, 0x75, 0xf5, 0x32, 0xb4, 0x42, 0x98, 0x8d, 0x16, 0xfc, 0xdd, 0x45, 0x33,
	0xd9, 0x48, 0x2d, 0x59, 0xb5, 0x18, 0x0a, 0xb3, 0xbc, 0x12, 0x0b, 0x56, 0xc3, 0xaa, 0xd1, 0xb3,
	0x49, 0x30, 0x8d, 0x76, 0x9f, 0x3f, 0x8e, 0x4d, 0x89, 0xb8, 0x2f, 0x39, 0xce, 0x13, 0xa7, 0x20,
	0x9b, 0xe4, 0xdd, 0xf9, 0xda, 0x77, 0x2e, 0xd7, 0xbe, 0x6f, 0xe2, 0x6f, 0x0a, 0x0a, 0x7f, 0xfc,
	0xf6, 0xa3, 0x52, 0xea, 0x8f, 0xab, 0x3c, 0xe6, 0x50, 0x53, 0x3b, 0x94, 0xf9, 0x1c, 0xaa, 0x62,
	0x49, 0xf5, 0x59, 0x2b, 0xd4, 0x90, 0xa9, 0xb2, 0x87, 0x36, 0x26, 0x1d, 0x53, 0x8e, 0x87, 0x10,
	0xfc, 0x06, 0x79, 0x8c, 0x6b, 0x09, 0xcd, 0x82, 0x43, 0xdd, 0x56, 0x42, 0x8b, 0x62, 0x36, 0x0d,
	0xa6, 0xd1, 0x9d, 0xc4, 0xb7, 0x35, 0x1e, 0xd9, 0x29, 0xff, 0x73, 0x85, 0xd9, 0x7d, 0x43, 0xa5,
	0x23, 0xf3, 0xf4, 0x3d, 0xda, 0x39, 0x1e, 0x28, 0xbc, 0x87, 0x90, 0x39, 0xbd, 0x05, 0xbe, 0xf4,
	0x9c, 0x6b, 0x7c, 0x02, 0x5a, 0x78, 0x2e, 0x7e, 0x80, 0xf6, 0x0d, 0x4e, 0x3b, 0xc1, 0xb4, 0x38,
	0x61, 0xab, 0x4a, 0x7b, 0x13, 0xbc, 0x8f, 0xee, 0x19, 0xfa, 0x95, 0x68, 0x41, 0x49, 0xed, 0x4d,
	0xe7, 0xb7, 0xbe, 0x7c, 0x23, 0x4e, 0xf2, 0xfa, 0x7c, 0x43, 0xdc, 0x8b, 0x0d, 0x71, 0xff, 0x6c,
	0x88, 0xfb, 0x75, 0x4b, 0x9c, 0x8b, 0x2d, 0x71, 0x7e, 0x6d, 0x89, 0xf3, 0x81, 0xfe, 0x73, 0x03,
	0xfd, 0x8a, 0x1c, 0xc2, 0xe9, 0xa9, 0xe4, 0x92, 0x55, 0x16, 0xd3, 0x71, 0xad, 0x86, 0xeb, 0xc8,
	0x77, 0x86, 0x07, 0x7e, 0xf1, 0x37, 0x00, 0x00, 0xff, 0xff, 0x14, 0x73, 0x62, 0x7e, 0x73, 0x02,
	0x00, 0x00,
}

func (m *ClaimRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClaimRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClaimRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ActionCompleted) > 0 {
		for iNdEx := len(m.ActionCompleted) - 1; iNdEx >= 0; iNdEx-- {
			i--
			if m.ActionCompleted[iNdEx] {
				dAtA[i] = 1
			} else {
				dAtA[i] = 0
			}
		}
		i = encodeVarintClaim(dAtA, i, uint64(len(m.ActionCompleted)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.InitialClaimableAmount) > 0 {
		for iNdEx := len(m.InitialClaimableAmount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.InitialClaimableAmount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintClaim(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintClaim(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintClaim(dAtA []byte, offset int, v uint64) int {
	offset -= sovClaim(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ClaimRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovClaim(uint64(l))
	}
	if len(m.InitialClaimableAmount) > 0 {
		for _, e := range m.InitialClaimableAmount {
			l = e.Size()
			n += 1 + l + sovClaim(uint64(l))
		}
	}
	if len(m.ActionCompleted) > 0 {
		n += 1 + sovClaim(uint64(len(m.ActionCompleted))) + len(m.ActionCompleted)*1
	}
	return n
}

func sovClaim(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozClaim(x uint64) (n int) {
	return sovClaim(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ClaimRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClaim
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClaimRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClaimRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClaim
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClaim
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthClaim
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialClaimableAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClaim
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClaim
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthClaim
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InitialClaimableAmount = append(m.InitialClaimableAmount, types.Coin{})
			if err := m.InitialClaimableAmount[len(m.InitialClaimableAmount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType == 0 {
				var v int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowClaim
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.ActionCompleted = append(m.ActionCompleted, bool(v != 0))
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowClaim
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthClaim
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthClaim
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				elementCount = packedLen
				if elementCount != 0 && len(m.ActionCompleted) == 0 {
					m.ActionCompleted = make([]bool, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowClaim
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.ActionCompleted = append(m.ActionCompleted, bool(v != 0))
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field ActionCompleted", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipClaim(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthClaim
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipClaim(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowClaim
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowClaim
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowClaim
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthClaim
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupClaim
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthClaim
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthClaim        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowClaim          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupClaim = fmt.Errorf("proto: unexpected end of group")
)
